[package]
name = "sniff"
version = "0.1.0"
edition = "2021"
license = "MIT" 
description = "A simple ytdlp bulk download wrapper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
